# Generated by Django 6.1 on 2026-09-07 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypurchase',
            name='insured_is_self',
            field=models.BooleanField(default=True, help_text='Whether the customer is buying for themselves or someone else.'),
        ),
        migrations.AddField(
            model_name='policypurchase',
            name='kyc',
            field=models.ForeignKey(blank=True, help_text='The KYC covering the insured party for this purchase.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='documents.customerkyc'),
        ),
        migrations.AlterField(
            model_name='policypurchase',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending payment'), ('PAID', 'Paid — awaiting review'), ('FORWARDED', 'With provider for issuance'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
