# Generated by Django 6.1 on 2026-09-08 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_commission_rate'),
        ('purchases', '0002_policypurchase_insured_is_self_policypurchase_kyc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Premium collected on the sale.', max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percent snapshotted from the provider at issuance.', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Gross minus commission.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='providers.provider')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='purchases.policypurchase')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='purchases_p_status_e615b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('purchase',), name='one_payout_per_purchase')],
            },
        ),
    ]
