# Generated by Django 6.1 on 2026-09-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('WELCOME', 'Welcome'), ('PURCHASE_CREATED', 'Purchase created'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_FAILED', 'Payment failed'), ('PURCHASE_FORWARDED', 'Purchase forwarded'), ('POLICY_ISSUED', 'Policy issued'), ('RENEWAL_REMINDER', 'Renewal reminder'), ('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_UNDER_REVIEW', 'Claim under review'), ('CLAIM_MORE_INFO', 'Claim needs more information'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected'), ('CLAIM_SETTLED', 'Claim settled'), ('KYC_VERIFIED', 'KYC verified'), ('KYC_REJECTED', 'KYC rejected'), ('PROVIDER_APPROVED', 'Provider approved'), ('PROVIDER_NEW_ISSUANCE', 'New purchase to issue'), ('PROVIDER_NEW_CLAIM', 'New claim to review')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Frontend deep link the notification points at, e.g. /dashboard/claims/5.', max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
    ]
