# Generated by Django 6.1 on 2026-09-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('WELCOME', 'Welcome'), ('PURCHASE_CREATED', 'Purchase created'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_FAILED', 'Payment failed'), ('PURCHASE_FORWARDED', 'Purchase forwarded'), ('POLICY_ISSUED', 'Policy issued'), ('RENEWAL_REMINDER', 'Renewal reminder'), ('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_UNDER_REVIEW', 'Claim under review'), ('CLAIM_MORE_INFO', 'Claim needs more information'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected'), ('CLAIM_SETTLED', 'Claim settled'), ('KYC_VERIFIED', 'KYC verified'), ('KYC_REJECTED', 'KYC rejected'), ('PROVIDER_APPROVED', 'Provider approved'), ('PROVIDER_NEW_ISSUANCE', 'New purchase to issue'), ('PROVIDER_NEW_CLAIM', 'New claim to review'), ('POLICY_APPROVED', 'Policy approved'), ('POLICY_DEACTIVATED', 'Policy deactivated'), ('POLICY_REJECTED', 'Policy sent back for changes'), ('CLAIM_MESSAGE', 'New claim message')], max_length=30),
        ),
    ]
