# Generated by Django 6.1 on 2026-09-10 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, help_text="The actor's platform role snapshotted at action time.", max_length=40)),
                ('action', models.CharField(help_text="The permission/action used, e.g. 'kyc.approve'.", max_length=64)),
                ('module', models.CharField(blank=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Old/new values where relevant.')),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['action'], name='staff_audit_action_34103c_idx'), models.Index(fields=['entity_type', 'entity_id'], name='staff_audit_entity__9c345a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SYSTEM_OWNER', 'System Owner'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('KYC_COMPLIANCE_OFFICER', 'KYC & Compliance Officer'), ('POLICY_MODERATOR', 'Policy Moderator'), ('PROVIDER_RELATIONS', 'Provider Relations'), ('CLAIMS_OFFICER', 'Claims Officer'), ('FINANCE_OFFICER', 'Finance Officer'), ('TECHNICAL_ADMIN', 'Technical Administrator'), ('MARKETING_OFFICER', 'Marketing Officer'), ('LEGAL_ADVISOR', 'Legal / Regulatory Advisor')], max_length=40)),
                ('granted_by', models.ForeignKey(blank=True, help_text='The staff member who assigned this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_roles_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'role'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_staff_user_role')],
            },
        ),
    ]
