# Generated by Django 6.1 on 2026-09-08 17:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Platform commission percent charged on each sale of this provider's policies.", max_digits=5),
        ),
    ]
