# Generated by Django 6.1 on 2026-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_provider_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermembership',
            name='role',
            field=models.CharField(choices=[('COMPANY_ADMIN', 'Company Admin'), ('POLICY_MANAGER', 'Policy Manager'), ('CLAIMS_OFFICER', 'Claims Officer'), ('SALES_MANAGER', 'Sales / Relationship Manager'), ('FINANCE_VIEWER', 'Finance Viewer')], default='FINANCE_VIEWER', help_text='Owners are not stored here; the owner is Provider.user.', max_length=20),
        ),
    ]
