# Generated by Django 6.1 on 2026-08-27 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key the frontend maps to an SVG (e.g. heart, health, car, plane).', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers are shown first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'insurance category',
                'verbose_name_plural': 'insurance categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, help_text='One-line tagline for cards and previews.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One-time')], default='YEARLY', max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, help_text='Sum assured.', max_digits=14)),
                ('term_months', models.PositiveIntegerField(help_text='Policy duration in months.')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of highlight strings.')),
                ('add_ons', models.JSONField(blank=True, default=list, help_text='List of optional add-ons.')),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.insurancecategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='providers.provider')),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'policies',
                'ordering': ['-is_featured', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='policies_po_status_83d281_idx'), models.Index(fields=['category', 'status'], name='policies_po_categor_bf6bef_idx')],
            },
        ),
    ]
