# Generated by Django 6.1 on 2026-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Failed verification attempts against this code.'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='accounts_ot_user_id_2dc7bd_idx'),
        ),
    ]
