# Generated by Django 6.1 on 2026-09-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('ONBOARDED', 'Onboarded'), ('DECLINED', 'Declined')], default='NEW', max_length=20)),
            ],
            options={
                'verbose_name': 'provider lead',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['status'], name='leads_provi_status_4ab745_idx')],
            },
        ),
    ]
