# Generated by Django 6.1 on 2026-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlead',
            name='kind',
            field=models.CharField(choices=[('PROVIDER', 'Provider onboarding'), ('CONTACT', 'Contact enquiry')], default='PROVIDER', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerlead',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
