# Generated by Django 6.1 on 2026-09-07 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_self', models.BooleanField(default=True, help_text="The customer's own reusable KYC, versus a beneficiary's.")),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('OTHER', 'Other')], max_length=10)),
                ('family_details', models.TextField(blank=True, help_text='Spouse / parents / dependents as relevant to the policy.')),
                ('temporary_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField()),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('CITIZENSHIP', 'Citizenship'), ('NID', 'National ID card')], max_length=20)),
                ('document_number', models.CharField(max_length=60)),
                ('document_front', models.ImageField(upload_to='kyc/%Y/%m/')),
                ('document_back', models.ImageField(blank=True, null=True, upload_to='kyc/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Why a KYC was rejected — shown back to the customer.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer KYC',
                'verbose_name_plural': 'customer KYC records',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['customer', 'is_self', 'status'], name='documents_c_custome_fa8c2a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_self', True)), fields=('customer',), name='one_self_kyc_per_customer')],
            },
        ),
    ]
