# Generated by Django 6.1 on 2026-09-10 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('providers', '0004_alter_providermembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Company registration'), ('TAX', 'Tax / PAN registration'), ('LICENSE', 'Insurance licence'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='provider_kyc/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Why a document was rejected — shown back to the provider.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='providers.provider')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_kyc', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_provider_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider KYC document',
                'verbose_name_plural': 'provider KYC documents',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['provider', 'status'], name='documents_p_provide_57965c_idx')],
            },
        ),
    ]
