# Generated by Django 6.1 on 2026-08-27 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='policy_purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.policypurchase'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
